
// Code generated by go-shell-cli-option-parser DO NOT EDIT.

package kubectloptions

var KubeCtlGlobalOptions = []CLIOption{

	{
		ShortOption: "",
		LongOption: "add-dir-header",
		HasDefaultValue: true,
	},

	{
		ShortOption: "",
		LongOption: "alsologtostderr",
		HasDefaultValue: true,
	},

	{
		ShortOption: "",
		LongOption: "as",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "as-group",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "as-uid",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "cache-dir",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "certificate-authority",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "client-certificate",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "client-key",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "cluster",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "context",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "insecure-skip-tls-verify",
		HasDefaultValue: true,
	},

	{
		ShortOption: "",
		LongOption: "kubeconfig",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "log-backtrace-at",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "log-dir",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "log-file",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "log-file-max-size",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "log-flush-frequency",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "logtostderr",
		HasDefaultValue: true,
	},

	{
		ShortOption: "",
		LongOption: "match-server-version",
		HasDefaultValue: true,
	},

	{
		ShortOption: "n",
		LongOption: "namespace",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "one-output",
		HasDefaultValue: true,
	},

	{
		ShortOption: "",
		LongOption: "password",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "profile",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "profile-output",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "request-timeout",
		HasDefaultValue: false,
	},

	{
		ShortOption: "s",
		LongOption: "server",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "skip-headers",
		HasDefaultValue: true,
	},

	{
		ShortOption: "",
		LongOption: "skip-log-headers",
		HasDefaultValue: true,
	},

	{
		ShortOption: "",
		LongOption: "stderrthreshold",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "tls-server-name",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "token",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "user",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "username",
		HasDefaultValue: false,
	},

	{
		ShortOption: "v",
		LongOption: "v",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "",
		HasDefaultValue: false,
	},

	{
		ShortOption: "",
		LongOption: "warnings-as-errors",
		HasDefaultValue: true,
	},

}

var KubeCtlOptions = map[string][]CLIOption{

	"get": {
		
		{
			ShortOption: "A",
			LongOption: "all-namespaces",
			HasDefaultValue: true,
		},
		
		{
			ShortOption: "",
			LongOption: "allow-missing-template-keys",
			HasDefaultValue: true,
		},
		
		{
			ShortOption: "",
			LongOption: "chunk-size",
			HasDefaultValue: false,
		},
		
		{
			ShortOption: "",
			LongOption: "field-selector",
			HasDefaultValue: false,
		},
		
		{
			ShortOption: "f",
			LongOption: "filename",
			HasDefaultValue: false,
		},
		
		{
			ShortOption: "",
			LongOption: "ignore-not-found",
			HasDefaultValue: true,
		},
		
		{
			ShortOption: "k",
			LongOption: "kustomize",
			HasDefaultValue: false,
		},
		
		{
			ShortOption: "L",
			LongOption: "label-columns",
			HasDefaultValue: false,
		},
		
		{
			ShortOption: "",
			LongOption: "no-headers",
			HasDefaultValue: true,
		},
		
		{
			ShortOption: "o",
			LongOption: "output",
			HasDefaultValue: false,
		},
		
		{
			ShortOption: "",
			LongOption: "output-watch-events",
			HasDefaultValue: true,
		},
		
		{
			ShortOption: "",
			LongOption: "raw",
			HasDefaultValue: false,
		},
		
		{
			ShortOption: "R",
			LongOption: "recursive",
			HasDefaultValue: true,
		},
		
		{
			ShortOption: "l",
			LongOption: "selector",
			HasDefaultValue: false,
		},
		
		{
			ShortOption: "",
			LongOption: "server-print",
			HasDefaultValue: true,
		},
		
		{
			ShortOption: "",
			LongOption: "show-kind",
			HasDefaultValue: true,
		},
		
		{
			ShortOption: "",
			LongOption: "show-labels",
			HasDefaultValue: true,
		},
		
		{
			ShortOption: "",
			LongOption: "show-managed-fields",
			HasDefaultValue: true,
		},
		
		{
			ShortOption: "",
			LongOption: "sort-by",
			HasDefaultValue: false,
		},
		
		{
			ShortOption: "",
			LongOption: "subresource",
			HasDefaultValue: false,
		},
		
		{
			ShortOption: "",
			LongOption: "template",
			HasDefaultValue: false,
		},
		
		{
			ShortOption: "w",
			LongOption: "watch",
			HasDefaultValue: true,
		},
		
		{
			ShortOption: "",
			LongOption: "watch-only",
			HasDefaultValue: true,
		},
		
	},

}
