name: Go tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20' ]

    steps:
      - uses: actions/checkout@v3

      # Solve errors on /nektos/act
      - name: Install packages
        if: ${{ env.ACT }}
        run: |
          # https://github.com/actions/setup-go/issues/220#issuecomment-1117998068
          apt-get update && apt-get install -y --no-install-recommends \
            ca-certificates

          # To fix an error on runtime/cgo
          apt-get install -y --no-install-recommends \
            build-essential \
            gcc

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get ./...
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
